// DO NOT EDIT! This test has been generated by tools/gentest.py.
// OffscreenCanvas test in a worker:2d.state.saverestore.lineJoin
// Description:save()/restore() works for lineJoin
// Note:

importScripts("/resources/testharness.js");
importScripts("/2dcontext/resources/canvas-tests.js");

promise_test(function(t) {

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');

// Test that restore() undoes any modifications
var old = ctx.lineJoin;
ctx.save();
ctx.lineJoin = "round";
ctx.restore();
_assertSame(ctx.lineJoin, old, "ctx.lineJoin", "old");

// Also test that save() doesn't modify the values
ctx.lineJoin = "round";
old = ctx.lineJoin;
    // we're not interested in failures caused by get(set(x)) != x (e.g.
    // from rounding), so compare against 'old' instead of against "round"
ctx.save();
_assertSame(ctx.lineJoin, old, "ctx.lineJoin", "old");
ctx.restore();

return Promise.resolve();
}, "save()/restore() works for lineJoin");
done();
