// DO NOT EDIT! This test has been generated by tools/gentest.py.
// OffscreenCanvas test in a worker:2d.state.saverestore.stack
// Description:save()/restore() can be nested as a stack
// Note:

importScripts("/resources/testharness.js");
importScripts("/2dcontext/resources/canvas-tests.js");

promise_test(function(t) {

var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');

ctx.lineWidth = 1;
ctx.save();
ctx.lineWidth = 2;
ctx.save();
ctx.lineWidth = 3;
_assertSame(ctx.lineWidth, 3, "ctx.lineWidth", "3");
ctx.restore();
_assertSame(ctx.lineWidth, 2, "ctx.lineWidth", "2");
ctx.restore();
_assertSame(ctx.lineWidth, 1, "ctx.lineWidth", "1");

return Promise.resolve();
}, "save()/restore() can be nested as a stack");
done();
